version: 1.0.{build}
build:
  verbosity: normal

platform:
  - x86
  - Any CPU

configuration:
  - Release

artifacts:
  - path: GraphiteClientGenerator\bin\Release\GraphiteClientGenerator.exe
    name: Release

deploy:
  - provider: GitHub
    artifact: Release
    auth_token:
      secure: EASr2nhRTqMf+jagPdEmWTlzrquvXFGYMpHF3DmylVEkdPmI+fbnRWbM26pGSZO2
    on:
      branch: master